[package]
name = "keygen"
version = "0.1.0"
edition = "2021"

[dependencies]
bls12_381 = "0.7.0"
ff = "0.13"
group = "0.12.1"
hex = "0.4"
rand = { version = "0.8", features = ["std_rng"] }
sha2 = "0.9"
hkdf = "0.11"
serde_json = "1.0.91"
structopt = "0.3"
serde_derive = "1.0.152"
serde = "1.0"
